# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nblog.proto\x12\x04\x62log\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n\x04\x42log\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12+\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cis_published\x18\x05 \x01(\x08\x12\x0f\n\x07user_id\x18\x06 \x01(\x05\"\x19\n\x0b\x42logRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x10\x42logListResponse\x12\x19\n\x05\x62logs\x18\x01 \x03(\x0b\x32\n.blog.Blog\"S\n\nBlogCreate\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x14\n\x0cis_published\x18\x05 \x01(\x08\x12\x0f\n\x07user_id\x18\x06 \x01(\x05\x32\xef\x01\n\x0b\x42logService\x12\'\n\x04Read\x12\x11.blog.BlogRequest\x1a\n.blog.Blog\"\x00\x12(\n\x06\x43reate\x12\x10.blog.BlogCreate\x1a\n.blog.Blog\"\x00\x12\x38\n\x04List\x12\x16.google.protobuf.Empty\x1a\x16.blog.BlogListResponse\"\x00\x12(\n\x06Update\x12\x10.blog.BlogCreate\x1a\n.blog.Blog\"\x00\x12)\n\x06\x44\x65lete\x12\x11.blog.BlogRequest\x1a\n.blog.Blog\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOG']._serialized_start=83
  _globals['_BLOG']._serialized_end=217
  _globals['_BLOGREQUEST']._serialized_start=219
  _globals['_BLOGREQUEST']._serialized_end=244
  _globals['_BLOGLISTRESPONSE']._serialized_start=246
  _globals['_BLOGLISTRESPONSE']._serialized_end=291
  _globals['_BLOGCREATE']._serialized_start=293
  _globals['_BLOGCREATE']._serialized_end=376
  _globals['_BLOGSERVICE']._serialized_start=379
  _globals['_BLOGSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
